"""Request and response models for the HTTP API."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

LanguageCode = Literal["en", "hi", "mr"]
JurisdictionChoice = Literal["india", "international", "both"]
SESSION_ID_PATTERN = r"^[A-Za-z0-9_-]{8,64}$"


# --- Health ---------------------------------------------------------------
class LlmStatus(BaseModel):
    provider: str
    model: str
    configured: bool


class CorpusStatus(BaseModel):
    raw_files: int
    manifest_entries: int = 0
    documents: int = 0
    chunks: int = 0


class Features(BaseModel):
    admin_mode: bool
    reranker: bool
    citation_verification: bool
    translator: str | None


class HealthResponse(BaseModel):
    status: str
    app: str
    version: str
    llm: LlmStatus
    embedding_model: str
    corpus: CorpusStatus
    features: Features


# --- Chat -----------------------------------------------------------------
class ChatRequest(BaseModel):
    session_id: str = Field(pattern=SESSION_ID_PATTERN, description="Anonymous id generated by the browser")
    message: str = Field(min_length=1, max_length=2000)
    language: LanguageCode = "en"
    jurisdiction: JurisdictionChoice = "india"
    quick_reply_id: str | None = Field(default=None, max_length=100, description="Id of a clicked quick-reply button")


class QuickReply(BaseModel):
    id: str
    label: str


class Citation(BaseModel):
    marker: int = Field(description="The number used in the answer text, e.g. 2 for [S2]")
    chunk_id: str
    doc_id: str
    doc_title: str
    section_ref: str
    jurisdiction: str
    version_date: str
    version: str = Field(description="Short hash of the ingested file")
    source_url: str
    file: str
    page: int | None
    snippet: str


class AnswerBlock(BaseModel):
    jurisdiction: Literal["india", "international"]
    markdown: str
    citations: list[Citation]
    confidence: float
    confidence_label: Literal["high", "medium", "low"]
    abstained: bool
    abstain_reason: str | None = None
    mode: Literal["generated", "extractive", "abstained"] = "generated"
    escalation_suggested: bool = False
    signals: dict[str, float] = Field(default_factory=dict, description="Confidence components (for transparency)")


class ChatResponse(BaseModel):
    query_id: int | None
    answers: dict[str, AnswerBlock]
    follow_up_question: str | None = None
    quick_replies: list[QuickReply] = Field(default_factory=list)
    notice: str | None = Field(default=None, description="A note shown above the answers (e.g. scope limits)")
    intents: list[str] = Field(default_factory=list)
    disclaimer: str
    language: LanguageCode


# --- Escalation ---------------------------------------------------------------
class EscalateRequest(BaseModel):
    session_id: str = Field(pattern=SESSION_ID_PATTERN)
    query_id: int | None = None
    jurisdiction: Literal["india", "international"] | None = None
    language: LanguageCode = "en"
    note: str = Field(default="", max_length=1000)


class EscalateResponse(BaseModel):
    status: Literal["recorded"]
    reference: str
    message: str


# --- Feedback ----------------------------------------------------------------
class FeedbackRequest(BaseModel):
    session_id: str = Field(pattern=SESSION_ID_PATTERN)
    query_id: int | None = None
    jurisdiction: Literal["india", "international"] | None = None
    rating: Literal["up", "down"]
    comment: str = Field(default="", max_length=1000)


class FeedbackResponse(BaseModel):
    status: Literal["recorded"]


# --- Admin / audit --------------------------------------------------------------
class AdminStats(BaseModel):
    queries: int
    abstention_rate: float | None
    avg_confidence: float | None
    feedback_up: int
    feedback_down: int
    escalations: int
    by_language: dict[str, int]


class AdminQuery(BaseModel):
    id: int
    created_at: str
    language: str
    jurisdiction: str
    query_text: str
    intents: list[str]
    blocks: dict
    min_confidence: float | None
    abstained: bool
    latency_ms: int
    llm_provider: str
    source: str


class AdminFeedback(BaseModel):
    id: int
    query_id: int | None
    jurisdiction: str | None
    rating: str
    comment: str
    created_at: str


class AdminEscalation(BaseModel):
    id: int
    reference: str
    query_id: int | None
    jurisdiction: str | None
    language: str
    note: str
    status: str
    created_at: str


class AdminOverview(BaseModel):
    stats: AdminStats
    queries: list[AdminQuery]
    feedback: list[AdminFeedback]
    escalations: list[AdminEscalation]


# --- Sources ----------------------------------------------------------------
class SourceVersion(BaseModel):
    version: str
    version_date: str
    ingested_at: str
    chunk_count: int
    active: bool


class SourceDocument(BaseModel):
    id: str
    title: str
    jurisdiction: str
    domain: str
    doc_type: str
    source_url: str
    file: str
    status: Literal["ingested", "pending", "missing_file", "removed_from_manifest"]
    active_version: SourceVersion | None
    versions: list[SourceVersion]


class SourcesResponse(BaseModel):
    documents: list[SourceDocument]
    manifest_error: str | None = None
